Add Report Accident Modal
BuildForSDG/Team-079-Frontend pull request #9
Opened 2020-05-26 10:18 UTC by fisayo-DMG

## Description
Adds the report accident button which shows the report form in a modal. The button should be used on the landing page.

Fixes #7

2020-05-26 13:59 UTC, Techiefrankie requested changes
Everything looks good to me. Please can you remove all commented codes not used to make code more readable and concise, and also to meet the standards we have adopted.

2020-05-26 13:59 UTC, Techiefrankie commented on src/components/ReportModal.js
> +        // viewport_ne_lat: 40.7137011802915,
Please remove unused codes in comments

2020-06-02 09:21 UTC, fisayo-DMG commented on src/components/ReportModal.js
> +        // viewport_ne_lat: 40.7137011802915,
The comments have been removed.

2020-06-02 09:44 UTC, Techiefrankie commented
@fisayo-DMG please could do a pull from develop branch to update your local with the changes that @haffs0 made that was merged into the develop? This is to avoid a merge conflict. Thank you.

2020-06-02 09:47 UTC, fisayo-DMG commented
I did that already.

On 2 Jun 2020 10:44, "Franklyn Ogbonna" <notifications@github.com> wrote:

@fisayo-DMG <https://github.com/fisayo-DMG> please could do a pull from
develop branch to update your local with the changes that @haffs0
<https://github.com/haffs0> made that was merged into the develop? This is
to avoid a merge conflict. Thank you.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/BuildForSDG/Team-079-Frontend/pull/9#issuecomment-637424659>,
or unsubscribe
<https://github.com/notifications/unsubscribe-auth/AEAHJFQP76A6PAX5GK757WTRUTCYFANCNFSM4NKFSKBQ>
.

2020-06-02 10:12 UTC, Techiefrankie commented
Great then. Thanks.

2020-06-02 10:12 UTC, Techiefrankie approved these changes

2020-06-02 10:13 UTC, merged